=== amiragomaa2597/xml-lab-3-/EmpXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Street"/>
				<xs:element ref="Building_Number"/>
				<xs:element ref="Region"/>
				<xs:element ref="City"/>
				<xs:element ref="Country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Building_Number" type="xs:string"/>
	<xs:element name="City" type="xs:string"/>
	<xs:element name="Country" type="xs:string"/>
	<xs:element name="E_mail" type="xs:string"/>
	<xs:element name="Employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Phones"/>
				<xs:element ref="Addresses"/>
				<xs:element ref="E_mail"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="Phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Home"/>
								<xs:enumeration value="Mobile"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Region" type="xs:string" />
	<xs:element name="Street" type="xs:string"/>
</xs:schema>

=== amiragomaa2597/xml-lab-3-/Untitled1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Untitled2.xsl"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/iti%209%20months%20scholarship%20program/labs/XML/lab1/Assignment%201/EmpXSD.xsd">
<!--<!DOCTYPE Employees SYSTEM "Untitled4.dtd">-->
	<Employee>
		<Name>Sherin</Name>
		<Phones>
			<Phone Type="Home">035267898</Phone>
			<Phone Type="Mobile">01023456748</Phone>
		</Phones>
		<Addresses>
			<Address>
				<Street>Street 1,</Street>
				<Building_Number>64</Building_Number>
				<Region>Region 1</Region>
				<City>Alex</City>
				<Country>Egypt</Country>
			</Address>
			<Address>
				<Street>Street 2,</Street>
				<Building_Number>64</Building_Number>
				<Region>Region 2</Region>
				<City>Cairo</City>
				<Country>Egypt</Country>
			</Address>
		</Addresses>
		<E_mail>sherin.reda15@gmail.com</E_mail>
	</Employee>
	<Employee>
		<Name>Rewan</Name>
		<Phones>
			<Phone Type="Home">035267898</Phone>
			<Phone Type="Mobile">01023456748</Phone>
		</Phones>
		<Addresses>
			<Address>
				<Street>Street 3,</Street>
				<Building_Number>65</Building_Number>
				<Region>Region 3</Region>
				<City>Cairo</City>
				<Country>Egypt</Country>
			</Address>
		</Addresses>
		<E_mail>rewan.ali15@gmail.com</E_mail>
	</Employee>
</Employees>
